name: xcube-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.5
  # runtime
  - dask=0.17.2
  - gdal=2.2.4
  - matplotlib=2.1.1
  - numpy=1.14.3
  - pandas=0.22.0
  - s3transfer=0.1.13
  - xarray=0.10.4
  - zarr=2.2.0
  # development/testing
  - pytest
