name: xcube-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.6
  #
  # runtime dependencies
  #
  - boto3 =1.9.2
  - botocore =1.12.3
  - dask =0.19.1
  - gdal =2.2.4
  - matplotlib =2.2.3
  - numpy =1.15.1
  - pandas =0.23.4
  - pyyaml =3.13
  - s3fs =0.1.6
  - scipy =1.1.0
  - xarray =0.10.8
  - zarr =2.2.0
  #
  # development dependencies
  #
  - flake8 =3.5.0
  - pytest =3.8.0
  - pytest-cov =2.6.0
