name: xcube-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.5
  # libs
  - dask=0.17.2
  - matplotlib=2.1.1
  - numpy=1.14.2
  - pandas=0.22.0
  - rasterio=0.36.0
  - s3transfer=0.1.13
  - scipy=1.0.1
  - tornado=5.0.2
  - xarray=0.10.3
  - zarr=2.2.0
